kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-wireguard-remote
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: semaphore-wireguard-remote
subjects:
- kind: ServiceAccount
  name: semaphore-wireguard-remote
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: semaphore-wireguard-remote
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: semaphore-wireguard-remote
  namespace: kube-system
