apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - daemonset.yaml
  - rbac.yaml
configMapGenerator:
  - name: semaphore-wireguard-config
    files:
     - config.json=resources/semaphore-wireguard-config.json
secretGenerator:
  - name: semaphore-wireguard-token-remote
    type: Opaque
    files:
      - token=secrets/semaphore-wireguard-token-remote
images:
  - name: semaphore-wireguard
    newName: quay.io/utilitywarehouse/semaphore-wireguard
    newTag: latest
